export const IS_DATA_LOADING = "IS_DATA_LOADING";
export const SET_PRODUCT_DATA = "SET_PRODUCT_DATA";
export const SET_PRODUCT_ERROR = "SET_PRODUCT_ERROR";

export const IS_PRODUCT_DATA_LOADING = "IS_PRODUCT_DATA_LOADING";
export const PRODUCT_DETAILS_DATA = "PRODUCT_DETAILS_DATA";
export const PRODUCT_DETAILS_ERROR = "PRODUCT_DETAILS_ERROR";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_CHANGE_ITEM = "CART_CHANGE_ITEM";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
